apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /knative-serving
  name: knative-serving
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|knative-serving'
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata: # kpt-merge: knative-serving/knative-serving
  name: knative-serving
  namespace: knative-serving
  annotations:
    internal.kpt.dev/upstream-identifier: 'operator.knative.dev|KnativeServing|knative-serving|knative-serving'
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
