apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: argo-events/argo-events-webhook-sa
  name: argo-events-webhook-sa
  namespace: argo-events
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|argo-events|argo-events-webhook-sa'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /argo-events-webhook
  name: argo-events-webhook
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|argo-events-webhook'
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - eventbus
  - eventsources
  - sensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /argo-events-webhook-binding
  name: argo-events-webhook-binding
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|argo-events-webhook-binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-webhook
subjects:
- kind: ServiceAccount
  name: argo-events-webhook-sa
  namespace: argo-events
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: argo-events/events-webhook
  name: events-webhook
  namespace: argo-events
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|argo-events|events-webhook'
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: events-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: argo-events/events-webhook
  name: events-webhook
  namespace: argo-events
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|argo-events|events-webhook'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-webhook
  template:
    metadata:
      labels:
        app: events-webhook
    spec:
      containers:
      - args:
        - webhook-service
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "443"
        image: quay.io/argoproj/argo-events:v1.9.4
        imagePullPolicy: Always
        name: webhook
      serviceAccountName: argo-events-webhook-sa
